version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=Just a secret?
      - JWT_EXPIRES_IN=1h
      - JWT_ISSUER=MyApp
      - JWT_AUDIENCE=MyAppUsers
      # MySQL 配置
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=qwer1234
      - DB_NAME=test_db
      - DB_DIALECT=mysql
      # MongoDB 配置
      - MONGODB_URI=mongodb://mongo:27017/ChatBot
    depends_on:
      - mongo
      - mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mongodb_data:
  mysql_data:
